// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhaleDeck.Infrastructure.Persistence;

#nullable disable

namespace WhaleDeck.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20261009075912_PlatformFoundation")]
    partial class PlatformFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhaleDeck.Domain.Entities.AlertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<string>("AcknowledgedBySubject")
                        .HasColumnType("text")
                        .HasColumnName("acknowledged_by_subject");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fingerprint");

                    b.Property<DateTimeOffset>("FirstOccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_occurred_at_utc");

                    b.Property<DateTimeOffset>("LastOccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_occurred_at_utc");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_count");

                    b.Property<DateTimeOffset?>("RecoveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recovered_at_utc");

                    b.Property<Guid?>("RelatedJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_job_id");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset?>("SilencedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silenced_until_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("SummaryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary_code");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint", "State");

                    b.ToTable("alert_events", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.AlertEventHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_subject");

                    b.Property<Guid>("AlertEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_event_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("AlertEventId", "OccurredAtUtc");

                    b.ToTable("alert_event_history", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EvaluationWindowSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("evaluation_window_seconds");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ResourceSelectorJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resource_selector_json");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_type");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("ThresholdJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("threshold_json");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.ApplicationInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoUpdateEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_update_enabled");

                    b.Property<string>("CatalogAppId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("catalog_app_id");

                    b.Property<string>("ConfigSummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_summary_json");

                    b.Property<string>("DesiredVersion")
                        .HasColumnType("text")
                        .HasColumnName("desired_version");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("InstalledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at_utc");

                    b.Property<string>("InstalledBySubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("installed_by_subject");

                    b.Property<string>("InstalledVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("installed_version");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_id");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("application_installations", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.ApplicationResource", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("ApplicationId", "ResourceId", "Role");

                    b.ToTable("application_resources", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.ApplicationUpdateRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text")
                        .HasColumnName("error_summary");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("NewImageDigest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_image_digest");

                    b.Property<string>("OldImageDigest")
                        .HasColumnType("text")
                        .HasColumnName("old_image_digest");

                    b.Property<string>("PlanHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_hash");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("VersionPolicy")
                        .HasColumnType("text")
                        .HasColumnName("version_policy");

                    b.Property<bool>("WasRolledBack")
                        .HasColumnType("boolean")
                        .HasColumnName("was_rolled_back");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "StartedAtUtc");

                    b.ToTable("application_update_runs", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_subject");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.Property<string>("SourceIp")
                        .HasColumnType("text")
                        .HasColumnName("source_ip");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("ActorSubject", "OccurredAtUtc");

                    b.HasIndex("TargetType", "TargetId", "OccurredAtUtc");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.BackupPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CapacityCriticalPercent")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_critical_percent");

                    b.Property<int>("CapacityWarningPercent")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_warning_percent");

                    b.Property<string>("Compression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compression");

                    b.Property<Guid>("InstanceResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_resource_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("RetentionCount")
                        .HasColumnType("integer")
                        .HasColumnName("retention_count");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.Property<string>("ScheduleExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schedule_expression");

                    b.Property<string>("TargetDirectoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_directory_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<bool>("VerifyAfterBackup")
                        .HasColumnType("boolean")
                        .HasColumnName("verify_after_backup");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("backup_policies", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.BackupRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .HasColumnType("text")
                        .HasColumnName("checksum");

                    b.Property<string>("ChecksumAlgorithm")
                        .HasColumnType("text")
                        .HasColumnName("checksum_algorithm");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("InstanceResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_resource_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("RelativePath")
                        .HasColumnType("text")
                        .HasColumnName("relative_path");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("InstanceResourceId", "StartedAtUtc");

                    b.ToTable("backup_records", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.CatalogSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("SourceEtag")
                        .HasColumnType("text")
                        .HasColumnName("source_etag");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "FetchedAtUtc");

                    b.ToTable("catalog_snapshots", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.ConfigSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCommitSha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_commit_sha");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("branch");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBySubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_subject");

                    b.Property<string>("DiffSummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("diff_summary_json");

                    b.Property<string>("FileManifestJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("file_manifest_json");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_id");

                    b.Property<string>("ResultCommitSha")
                        .HasColumnType("text")
                        .HasColumnName("result_commit_sha");

                    b.Property<string>("SensitiveScanResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sensitive_scan_result");

                    b.HasKey("Id");

                    b.ToTable("config_snapshots", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.ConfigSyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AfterCommitSha")
                        .HasColumnType("text")
                        .HasColumnName("after_commit_sha");

                    b.Property<string>("BeforeCommitSha")
                        .HasColumnType("text")
                        .HasColumnName("before_commit_sha");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_id");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("config_sync_runs", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.ManagedResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("LabelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("labels_json");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("ProtectionLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protection_level");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProtectionLevel");

                    b.HasIndex("ResourceType", "ExternalId")
                        .IsUnique();

                    b.ToTable("managed_resources", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.MetricRollup", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<DateTimeOffset>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start_utc");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<double>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<double>("Maximum")
                        .HasColumnType("double precision")
                        .HasColumnName("maximum");

                    b.Property<double>("Minimum")
                        .HasColumnType("double precision")
                        .HasColumnName("minimum");

                    b.Property<long>("SampleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_count");

                    b.Property<double>("Sum")
                        .HasColumnType("double precision")
                        .HasColumnName("sum");

                    b.HasKey("SeriesId", "WindowStartUtc", "Resolution");

                    b.ToTable("metric_rollups", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.MetricSample", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<DateTimeOffset>("SampledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sampled_at_utc");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quality");

                    b.Property<double?>("ValueDouble")
                        .HasColumnType("double precision")
                        .HasColumnName("value_double");

                    b.HasKey("SeriesId", "SampledAtUtc");

                    b.HasIndex("SeriesId", "SampledAtUtc");

                    b.ToTable("metric_samples", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.MetricSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DimensionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dimensions_json");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("MetricKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_kind");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "MetricKind", "DimensionsJson")
                        .IsUnique();

                    b.ToTable("metric_series", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.OperationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_subject");

                    b.Property<Guid?>("AgentOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_operation_id");

                    b.Property<DateTimeOffset?>("CancelRequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancel_requested_at_utc");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_type");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<short?>("ProgressPercent")
                        .HasColumnType("smallint")
                        .HasColumnName("progress_percent");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_json");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ActorSubject", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ResourceId", "CreatedAtUtc");

                    b.HasIndex("State", "CreatedAtUtc");

                    b.ToTable("operation_jobs", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.OperationJobEvent", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<string>("MessageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_code");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<short?>("ProgressPercent")
                        .HasColumnType("smallint")
                        .HasColumnName("progress_percent");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("JobId", "Sequence");

                    b.ToTable("operation_job_events", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("last_error_code");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "AvailableAtUtc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.PlatformSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBySubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by_subject");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Key");

                    b.ToTable("platform_settings", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.PortalItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("description");

                    b.Property<string>("IconKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon_kind");

                    b.Property<string>("IconValue")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("icon_value");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_subject");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwnerSubject", "IsEnabled", "SortOrder");

                    b.HasIndex("Scope", "IsEnabled", "SortOrder");

                    b.ToTable("portal_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_portal_scope_owner", "(scope = 'Personal' AND owner_subject IS NOT NULL) OR (scope = 'Public' AND owner_subject IS NULL)");
                        });
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.PublicPortalPreference", b =>
                {
                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("PortalItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("portal_item_id");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Subject", "PortalItemId");

                    b.ToTable("public_portal_preferences", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.RoleMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthentikGroupId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authentik_group_id");

                    b.Property<string>("AuthentikGroupNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authentik_group_name_snapshot");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AuthentikGroupId")
                        .IsUnique();

                    b.ToTable("role_mappings", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.ScheduledTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyPolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_policy");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBySubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_subject");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NextRunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at_utc");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<string>("ScheduleExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schedule_expression");

                    b.Property<string>("ScheduleKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schedule_kind");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_type");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBySubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by_subject");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("scheduled_tasks", (string)null);
                });

            modelBuilder.Entity("WhaleDeck.Domain.Entities.ScheduledTaskRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTimeOffset>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for_utc");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId", "ScheduledForUtc");

                    b.ToTable("scheduled_task_runs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
